; highlights.scm
(console_command) @keyword
(label) @label
(instruction) @function
(block) @function
(identifier) @variable
(opcode) @keyword
(operand) @string
(number) @number
(string_literal) @string
(empty_line) @punctuation.delimiter
