(console_command) @operator
(label) @tag
(instruction) @function
(block) @constructor
(identifier) @variable
(opcode) @keyword
(operand) @property
(number) @number
(string_literal) @string
(empty_line) @punctuation.delimiter
